export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as MyPosts } from './MyPosts'
export { default as MyProfile } from './MyProfile'
export { default as Register } from './Register'
export { default as User } from './User'